name: Testing
on: push

env:
    UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          
jobs:
  test:
    name: Tests licence
    runs-on: ubuntu-latest
    steps:
    - name: Unity - Activate
      uses: game-ci/unity-activate@v2.0.0



      
