name: Testing
on:
  workflow_dispatch: {}
jobs:
  test:
    name: Tests licence
    runs-on: ubuntu-latest
    steps:
      - name: test
        uses: game-ci/unity-test-runner@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          projectPath: ProductiveAddiction\
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      
